apiVersion: apps/v1
kind: Deployment
metadata:
  name: basket-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: basket-operator
  template:
    metadata:
      labels:
        name: basket-operator
    spec:
      serviceAccountName: basket-operator
      containers:
        - name: basket-operator
          image: quay.io/srics/basket-operator
          command:
          - basket-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "basket-operator"
